services:

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"

  user-api:
    image: user-api:latest
    container_name: user-api
    ports:
      - "8080:8080"